version: '3'
services:
  app:
    image: myapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springdb?useUnicode=true&characterEncoding=UTF-8
    ports:
      - '8080:8080'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
