CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    mail VARCHAR(255),
    role VARCHAR(50) DEFAULT 'USER',
    is_online BOOLEAN DEFAULT FALSE
);
INSERT INTO users (username, password, mail, role, is_online)
VALUES ('admin', '1234', 'admin@test.com', 'USER', FALSE);
